### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Oshcakes** [kaelad02/show-secrets#2]
Secrets now showing in chat.
Fresh world created for this test.
![image](https://user-images.githubusercontent.com/61471647/153083443-bc506291-9db6-4083-a4a8-4f711725430b.png)

This is hosted on the forge though its not showing any errors in the console. 

Example 5e creature:
![image](https://user-images.githubusercontent.com/61471647/153083352-edc10044-aad7-41b7-8221-647e10809a13.png)

**Comment by kaelad02** [comment]
I tested it with v9 Build 238, and the same system version v1.5.7. It works with that setup. I also own ToB so I tried that specific actor and it works too. I'll try updating Foundry to see if there's something specific with that build that's causing the issue.

**Comment by kaelad02** [comment]
Nothing to do with the build. The manifest is missing a dependency on lib-wrapper. It needs that to work and it's not there. I was testing with a couple other modules that already include it so I didn't notice.

**Comment by kaelad02** [comment]
Version 1.1 is up and listed with Foundry's website. You can update the module and it'll require you to enable lib-wrapper, which is necessary for it to work.
